// <auto-generated />
using System;
using DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataModel.Migrations
{
    [DbContext(typeof(UserAccountDbContext))]
    [Migration("20241128010337_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataModel.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountId"));

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("RoutingNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("routing_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("AccountId")
                        .HasName("PK__accounts__46A222CD28174167");

                    b.HasIndex("UserId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("DataModel.Card", b =>
                {
                    b.Property<long>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CardId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Cvv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cvv");

                    b.Property<string>("Expiration")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("expiration");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("CardId")
                        .HasName("PK__cards__BDF201DD35D80F04");

                    b.HasIndex("AccountId");

                    b.HasIndex("UserId");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("DataModel.Entry", b =>
                {
                    b.Property<long>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EntryId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("EntryId")
                        .HasName("PK__entries__810FDCE13F7A44B9");

                    b.HasIndex("AccountId");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("DataModel.Loan", b =>
                {
                    b.Property<long>("LoadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("load_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LoadId"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("Interest")
                        .HasColumnType("int")
                        .HasColumnName("interest");

                    b.Property<string>("IssueDate")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("issue_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoadId")
                        .HasName("PK__loans__08CE0C5AE8683318");

                    b.HasIndex("UserId");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("DataModel.Transfer", b =>
                {
                    b.Property<long>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transfer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransferId"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("FromAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_account_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<long>("ToAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_account_id");

                    b.HasKey("TransferId")
                        .HasName("PK__transfer__78E6FD33B9BF9DEC");

                    b.HasIndex("FromAccountId");

                    b.HasIndex("ToAccountId");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("DataModel.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("number");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F40A936FB");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DataModel.Account", b =>
                {
                    b.HasOne("DataModel.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__accounts__user_i__30F848ED");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModel.Card", b =>
                {
                    b.HasOne("DataModel.Account", "Account")
                        .WithMany("Cards")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__cards__account_i__35BCFE0A");

                    b.HasOne("DataModel.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__cards__user_id__34C8D9D1");

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModel.Entry", b =>
                {
                    b.HasOne("DataModel.Account", "Account")
                        .WithMany("Entries")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__entries__account__33D4B598");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DataModel.Loan", b =>
                {
                    b.HasOne("DataModel.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__loans__user_id__36B12243");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModel.Transfer", b =>
                {
                    b.HasOne("DataModel.Account", "FromAccount")
                        .WithMany("TransferFromAccounts")
                        .HasForeignKey("FromAccountId")
                        .IsRequired()
                        .HasConstraintName("FK__transfers__from___31EC6D26");

                    b.HasOne("DataModel.Account", "ToAccount")
                        .WithMany("TransferToAccounts")
                        .HasForeignKey("ToAccountId")
                        .IsRequired()
                        .HasConstraintName("FK__transfers__to_ac__32E0915F");

                    b.Navigation("FromAccount");

                    b.Navigation("ToAccount");
                });

            modelBuilder.Entity("DataModel.Account", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Entries");

                    b.Navigation("TransferFromAccounts");

                    b.Navigation("TransferToAccounts");
                });

            modelBuilder.Entity("DataModel.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Cards");

                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
